language: python
matrix:
  include:
  - os: linux
    dist: xenial
    services:
      - xvfb
    sudo: false
    python: '3.6'
  - os: linux
    dist: xenial
    services:
      - xvfb
    sudo: false
    python: 3.7
cache:
  apt: true
  pip: true
  ccache: true
  directories:

addons:
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - gfortran

before_install:
# - if [[ "$TRAVIS_PYTHON_VERSION" != "3.4" && "$TRAVIS_PYTHON_VERSION" != "3.5" ]];
#   then pip install pyqt5; else source $TRAVIS_BUILD_DIR/.travis/build_pyqt5.sh; fi
- pip install matplotlib
- pip install pytest-cov
# - pip install sphinx
# - pip install numpydoc
# - pip install sphinx_rtd_theme
install:
- pip install -qq --upgrade pip setuptools wheel
# - cd $TRAVIS_BUILD_DIR
# - if [[ "$TRAVIS_PYTHON_VERSION" != "3.4" && "$TRAVIS_PYTHON_VERSION" != "3.5" ]];
#   then python setup.py egg_info;
#   python setup.py dist_info;
#   python setup.py build_sphinx;
#   python setup.py sdist; 
#   fi
# - if [[ "$TRAVIS_PYTHON_VERSION" != "3.4" && "$TRAVIS_PYTHON_VERSION" != "3.5" ]];
#   then python setup.py egg_info;
#   python setup.py dist_info;
#   python setup.py sdist; 
#   fi
- python setup.py install
- pwd
- ls
# - cd crikit2
# - python setup.py sdist
# - cd $TRAVIS_BUILD_DIR/docs/
# - sphinx-apidoc -o ./source ../sciplot
# - make html
# - pip uninstall -y sciplot-pyqt
# - cd $TRAVIS_BUILD_DIR
# - python setup.py install
script:
  - pytest --cov-report term

after_success:
  # - codecov