# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_CompositeColor.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(635, 480)
        Form.setStyleSheet("font: 10pt \"Arial\";")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.checkBoxFixed = QtWidgets.QCheckBox(self.frame_2)
        self.checkBoxFixed.setChecked(False)
        self.checkBoxFixed.setObjectName("checkBoxFixed")
        self.verticalLayout_5.addWidget(self.checkBoxFixed)
        self.checkBoxCompress = QtWidgets.QCheckBox(self.frame_2)
        self.checkBoxCompress.setChecked(False)
        self.checkBoxCompress.setObjectName("checkBoxCompress")
        self.verticalLayout_5.addWidget(self.checkBoxCompress)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.lineEditMin = QtWidgets.QLineEdit(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditMin.sizePolicy().hasHeightForWidth())
        self.lineEditMin.setSizePolicy(sizePolicy)
        self.lineEditMin.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEditMin.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEditMin.setObjectName("lineEditMin")
        self.verticalLayout_2.addWidget(self.lineEditMin)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.lineEditMax = QtWidgets.QLineEdit(self.frame_2)
        self.lineEditMax.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEditMax.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEditMax.setObjectName("lineEditMax")
        self.verticalLayout_3.addWidget(self.lineEditMax)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setFrameShape(QtWidgets.QFrame.VLine)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout.addWidget(self.frame)
        self.checkBoxRemOutliers = QtWidgets.QCheckBox(self.frame_2)
        self.checkBoxRemOutliers.setObjectName("checkBoxRemOutliers")
        self.horizontalLayout.addWidget(self.checkBoxRemOutliers)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.spinBoxStdDevs = QtWidgets.QDoubleSpinBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxStdDevs.sizePolicy().hasHeightForWidth())
        self.spinBoxStdDevs.setSizePolicy(sizePolicy)
        self.spinBoxStdDevs.setProperty("value", 3.0)
        self.spinBoxStdDevs.setObjectName("spinBoxStdDevs")
        self.verticalLayout_4.addWidget(self.spinBoxStdDevs)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout.addWidget(self.frame_2, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.checkBoxFixed.setText(_translate("Form", "Fixed"))
        self.checkBoxCompress.setText(_translate("Form", "Compress"))
        self.label_2.setText(_translate("Form", "Minimum"))
        self.label.setText(_translate("Form", "Maximum"))
        self.checkBoxRemOutliers.setText(_translate("Form", "Outlier Removal"))
        self.label_3.setText(_translate("Form", "Std. Dev\'s"))

