# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_CalcAnscombeParameters.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(635, 586)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setContentsMargins(-1, -1, -1, 20)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setMinimumSize(QtCore.QSize(0, 140))
        self.textEdit.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.textEdit.setFrameShape(QtWidgets.QFrame.Box)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_2.addWidget(self.textEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 10, 10, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, -1, -1, 20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setTextFormat(QtCore.Qt.RichText)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.checkBoxDarkSub = QtWidgets.QCheckBox(Dialog)
        self.checkBoxDarkSub.setObjectName("checkBoxDarkSub")
        self.verticalLayout.addWidget(self.checkBoxDarkSub)
        self.checkBoxAllFreqRange = QtWidgets.QCheckBox(Dialog)
        self.checkBoxAllFreqRange.setChecked(False)
        self.checkBoxAllFreqRange.setObjectName("checkBoxAllFreqRange")
        self.verticalLayout.addWidget(self.checkBoxAllFreqRange)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.spinBoxNSpectraDark = QtWidgets.QSpinBox(Dialog)
        self.spinBoxNSpectraDark.setMinimum(2)
        self.spinBoxNSpectraDark.setObjectName("spinBoxNSpectraDark")
        self.verticalLayout_3.addWidget(self.spinBoxNSpectraDark)
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_3.addWidget(self.label_9)
        self.spinBoxNSpectraRep = QtWidgets.QSpinBox(Dialog)
        self.spinBoxNSpectraRep.setMinimum(2)
        self.spinBoxNSpectraRep.setObjectName("spinBoxNSpectraRep")
        self.verticalLayout_3.addWidget(self.spinBoxNSpectraRep)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.spinBoxAxis = QtWidgets.QSpinBox(Dialog)
        self.spinBoxAxis.setMinimum(0)
        self.spinBoxAxis.setMaximum(1)
        self.spinBoxAxis.setObjectName("spinBoxAxis")
        self.verticalLayout_3.addWidget(self.spinBoxAxis)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(-1, 10, -1, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_5.addWidget(self.label_10)
        self.spinBoxSkipNDark = QtWidgets.QSpinBox(Dialog)
        self.spinBoxSkipNDark.setObjectName("spinBoxSkipNDark")
        self.verticalLayout_5.addWidget(self.spinBoxSkipNDark)
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_5.addWidget(self.label_11)
        self.spinBoxSkipNRep = QtWidgets.QSpinBox(Dialog)
        self.spinBoxSkipNRep.setObjectName("spinBoxSkipNRep")
        self.verticalLayout_5.addWidget(self.spinBoxSkipNRep)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.verticalLayout_5)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.spinBoxGMean = QtWidgets.QDoubleSpinBox(Dialog)
        self.spinBoxGMean.setReadOnly(True)
        self.spinBoxGMean.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxGMean.setDecimals(4)
        self.spinBoxGMean.setMaximum(1000000.0)
        self.spinBoxGMean.setObjectName("spinBoxGMean")
        self.verticalLayout_4.addWidget(self.spinBoxGMean)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.spinBoxGStdDev = QtWidgets.QDoubleSpinBox(Dialog)
        self.spinBoxGStdDev.setReadOnly(True)
        self.spinBoxGStdDev.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxGStdDev.setDecimals(4)
        self.spinBoxGStdDev.setMaximum(1000000.0)
        self.spinBoxGStdDev.setObjectName("spinBoxGStdDev")
        self.verticalLayout_4.addWidget(self.spinBoxGStdDev)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_4.addWidget(self.label_7)
        self.spinBoxAlphaMean = QtWidgets.QDoubleSpinBox(Dialog)
        self.spinBoxAlphaMean.setReadOnly(True)
        self.spinBoxAlphaMean.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxAlphaMean.setDecimals(4)
        self.spinBoxAlphaMean.setMaximum(1000000.0)
        self.spinBoxAlphaMean.setObjectName("spinBoxAlphaMean")
        self.verticalLayout_4.addWidget(self.spinBoxAlphaMean)
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_4.addWidget(self.label_8)
        self.spinBoxAlphaWMean = QtWidgets.QDoubleSpinBox(Dialog)
        self.spinBoxAlphaWMean.setReadOnly(True)
        self.spinBoxAlphaWMean.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxAlphaWMean.setDecimals(4)
        self.spinBoxAlphaWMean.setMaximum(1000000.0)
        self.spinBoxAlphaWMean.setObjectName("spinBoxAlphaWMean")
        self.verticalLayout_4.addWidget(self.spinBoxAlphaWMean)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.pushButtonOk = QtWidgets.QPushButton(Dialog)
        self.pushButtonOk.setAutoDefault(False)
        self.pushButtonOk.setObjectName("pushButtonOk")
        self.horizontalLayout_2.addWidget(self.pushButtonOk)
        self.pushButtonCancel = QtWidgets.QPushButton(Dialog)
        self.pushButtonCancel.setAutoDefault(False)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayout_2.addWidget(self.pushButtonCancel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Calculate Anscombe Parameters"))
        self.textEdit.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Note (1): if you will be defining a </span><span style=\" font-size:10pt; font-weight:600;\">Frequency Range</span><span style=\" font-size:10pt;\">, you should do it prior to this calculation.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Note (2): The default values that will be sent to the </span><span style=\" font-size:10pt; font-weight:600;\">Anscombe and Inverse Anscombe GUIs</span><span style=\" font-size:10pt;\"> will be the </span><span style=\" font-size:10pt; font-weight:600;\">Weighted Mean Alpha</span><span style=\" font-size:10pt;\"> value</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Note (3): This GUI can handle whether Dark has been subtracted or not. The actual Anscombe and Inverse Anscombe GUIs </span><span style=\" font-size:10pt; font-weight:600;\">cannot</span><span style=\" font-size:10pt;\">. This will be updated in the future.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p></body></html>"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Inputs</span></p></body></html>"))
        self.checkBoxDarkSub.setText(_translate("Dialog", "Dark Already Subtracted"))
        self.checkBoxAllFreqRange.setText(_translate("Dialog", "Use Entire Spectrum (False = Use Frequency Range)"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Use</span> N Dark Spectra for Calculation (Default = All)</p></body></html>"))
        self.label_9.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Use</span> N Rep Spectra for Calculation (Default = All)</p></body></html>"))
        self.label_2.setText(_translate("Dialog", "Non-Spectral Axis"))
        self.label_10.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Skip</span> first N Dark Spectra</p></body></html>"))
        self.label_11.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Skip</span> first N Rep Spectra</p></body></html>"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Outputs</span></p></body></html>"))
        self.label_5.setText(_translate("Dialog", "Gaussian Mean"))
        self.label_6.setText(_translate("Dialog", "Gaussian Std. Dev."))
        self.label_7.setText(_translate("Dialog", "Mean Alpha"))
        self.label_8.setText(_translate("Dialog", "Weighted Mean Alpha"))
        self.pushButtonOk.setText(_translate("Dialog", "OK"))
        self.pushButtonCancel.setText(_translate("Dialog", "Cancel"))
