# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_DarkOptions.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(235, 257)
        Dialog.setStyleSheet("font: 10pt \"Arial\";")
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 4, 0, 1, 1)
        self.checkBoxResidualDarkSub = QtWidgets.QCheckBox(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.checkBoxResidualDarkSub.setFont(font)
        self.checkBoxResidualDarkSub.setStyleSheet("font: 75 10pt \"Arial Black\";")
        self.checkBoxResidualDarkSub.setChecked(True)
        self.checkBoxResidualDarkSub.setObjectName("checkBoxResidualDarkSub")
        self.gridLayout_2.addWidget(self.checkBoxResidualDarkSub, 2, 0, 1, 1)
        self.frameDark = QtWidgets.QFrame(Dialog)
        self.frameDark.setFrameShape(QtWidgets.QFrame.Box)
        self.frameDark.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameDark.setObjectName("frameDark")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frameDark)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBoxDarkSubImg = QtWidgets.QCheckBox(self.frameDark)
        self.checkBoxDarkSubImg.setChecked(True)
        self.checkBoxDarkSubImg.setObjectName("checkBoxDarkSubImg")
        self.verticalLayout_2.addWidget(self.checkBoxDarkSubImg)
        self.checkBoxDarkSubNRB = QtWidgets.QCheckBox(self.frameDark)
        self.checkBoxDarkSubNRB.setChecked(True)
        self.checkBoxDarkSubNRB.setObjectName("checkBoxDarkSubNRB")
        self.verticalLayout_2.addWidget(self.checkBoxDarkSubNRB)
        self.gridLayout_2.addWidget(self.frameDark, 1, 0, 1, 1)
        self.frameResidual = QtWidgets.QFrame(Dialog)
        self.frameResidual.setEnabled(True)
        self.frameResidual.setFrameShape(QtWidgets.QFrame.Box)
        self.frameResidual.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameResidual.setObjectName("frameResidual")
        self.gridLayout = QtWidgets.QGridLayout(self.frameResidual)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.frameResidual)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.spinBoxMin = QtWidgets.QDoubleSpinBox(self.frameResidual)
        self.spinBoxMin.setMinimum(-10000.0)
        self.spinBoxMin.setMaximum(10000.0)
        self.spinBoxMin.setProperty("value", -1500.0)
        self.spinBoxMin.setObjectName("spinBoxMin")
        self.horizontalLayout.addWidget(self.spinBoxMin)
        self.spinBoxMax = QtWidgets.QDoubleSpinBox(self.frameResidual)
        self.spinBoxMax.setMinimum(-10000.0)
        self.spinBoxMax.setMaximum(10000.0)
        self.spinBoxMax.setProperty("value", -500.0)
        self.spinBoxMax.setObjectName("spinBoxMax")
        self.horizontalLayout.addWidget(self.spinBoxMax)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frameResidual, 3, 0, 1, 1)
        self.checkBoxDarkSub = QtWidgets.QCheckBox(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.checkBoxDarkSub.setFont(font)
        self.checkBoxDarkSub.setStyleSheet("font: 75 10pt \"Arial Black\";")
        self.checkBoxDarkSub.setChecked(True)
        self.checkBoxDarkSub.setObjectName("checkBoxDarkSub")
        self.gridLayout_2.addWidget(self.checkBoxDarkSub, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.rejected.connect(Dialog.reject)
        self.buttonBox.accepted.connect(Dialog.accept)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.checkBoxDarkSub, self.checkBoxDarkSubImg)
        Dialog.setTabOrder(self.checkBoxDarkSubImg, self.checkBoxDarkSubNRB)
        Dialog.setTabOrder(self.checkBoxDarkSubNRB, self.checkBoxResidualDarkSub)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dark Subtract Options"))
        self.checkBoxResidualDarkSub.setText(_translate("Dialog", "Residual Dark Subtraction"))
        self.checkBoxDarkSubImg.setText(_translate("Dialog", "Main Image"))
        self.checkBoxDarkSubNRB.setText(_translate("Dialog", "NRB (Background)"))
        self.label.setText(_translate("Dialog", "Frequency Range (cm-1)"))
        self.checkBoxDarkSub.setText(_translate("Dialog", "Dark Subtraction"))

