# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_Mosaic.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(953, 759)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayoutMPL = QtWidgets.QVBoxLayout()
        self.verticalLayoutMPL.setObjectName("verticalLayoutMPL")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayoutMPL.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayoutMPL.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.verticalLayoutMPL, 0, 0, 1, 2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEditFreq = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditFreq.sizePolicy().hasHeightForWidth())
        self.lineEditFreq.setSizePolicy(sizePolicy)
        self.lineEditFreq.setMinimumSize(QtCore.QSize(100, 30))
        self.lineEditFreq.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEditFreq.setFont(font)
        self.lineEditFreq.setStyleSheet("font: 14pt \"Arial\";")
        self.lineEditFreq.setObjectName("lineEditFreq")
        self.verticalLayout_2.addWidget(self.lineEditFreq, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.labelWavenumber_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelWavenumber_2.sizePolicy().hasHeightForWidth())
        self.labelWavenumber_2.setSizePolicy(sizePolicy)
        self.labelWavenumber_2.setMinimumSize(QtCore.QSize(120, 20))
        self.labelWavenumber_2.setMaximumSize(QtCore.QSize(1000, 20))
        self.labelWavenumber_2.setTextFormat(QtCore.Qt.AutoText)
        self.labelWavenumber_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelWavenumber_2.setObjectName("labelWavenumber_2")
        self.verticalLayout_2.addWidget(self.labelWavenumber_2, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sliderFreq = QtWidgets.QScrollBar(self.centralwidget)
        self.sliderFreq.setMinimumSize(QtCore.QSize(400, 30))
        self.sliderFreq.setProperty("value", 10)
        self.sliderFreq.setOrientation(QtCore.Qt.Horizontal)
        self.sliderFreq.setObjectName("sliderFreq")
        self.horizontalLayout.addWidget(self.sliderFreq)
        self.gridLayout_2.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        self.verticalLayoutOptions = QtWidgets.QVBoxLayout()
        self.verticalLayoutOptions.setObjectName("verticalLayoutOptions")
        self.gridLayout_2.addLayout(self.verticalLayoutOptions, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 953, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_HDF_NIST = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/open-iconic-master/png/envelope-open-4x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_HDF_NIST.setIcon(icon)
        self.actionOpen_HDF_NIST.setObjectName("actionOpen_HDF_NIST")
        self.menuFile.addAction(self.actionOpen_HDF_NIST)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelWavenumber_2.setText(_translate("MainWindow", "Wavenumber (cm-1)"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen_HDF_NIST.setText(_translate("MainWindow", "Open HDF NIST"))

from . import icons_all_rc
