# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_Model.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(395, 542)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayoutNoise = QtWidgets.QGridLayout()
        self.gridLayoutNoise.setObjectName("gridLayoutNoise")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayoutNoise.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.gridLayoutNoise.addWidget(self.label_5, 2, 1, 1, 1)
        self.checkBoxPNoise = QtWidgets.QCheckBox(Dialog)
        self.checkBoxPNoise.setObjectName("checkBoxPNoise")
        self.gridLayoutNoise.addWidget(self.checkBoxPNoise, 1, 1, 1, 1)
        self.checkBoxGNoise = QtWidgets.QCheckBox(Dialog)
        self.checkBoxGNoise.setObjectName("checkBoxGNoise")
        self.gridLayoutNoise.addWidget(self.checkBoxGNoise, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayoutNoise.addWidget(self.label_2, 0, 0, 1, 1)
        self.spinBoxPMulti = QtWidgets.QDoubleSpinBox(Dialog)
        self.spinBoxPMulti.setMinimum(1.0)
        self.spinBoxPMulti.setMaximum(100.0)
        self.spinBoxPMulti.setSingleStep(0.1)
        self.spinBoxPMulti.setProperty("value", 1.4)
        self.spinBoxPMulti.setObjectName("spinBoxPMulti")
        self.gridLayoutNoise.addWidget(self.spinBoxPMulti, 3, 1, 1, 1)
        self.spinBoxGStdDev = QtWidgets.QDoubleSpinBox(Dialog)
        self.spinBoxGStdDev.setMaximum(100000.0)
        self.spinBoxGStdDev.setSingleStep(0.1)
        self.spinBoxGStdDev.setProperty("value", 12.44)
        self.spinBoxGStdDev.setObjectName("spinBoxGStdDev")
        self.gridLayoutNoise.addWidget(self.spinBoxGStdDev, 3, 0, 1, 1)
        self.checkBoxDark = QtWidgets.QCheckBox(Dialog)
        self.checkBoxDark.setObjectName("checkBoxDark")
        self.gridLayoutNoise.addWidget(self.checkBoxDark, 1, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.gridLayoutNoise.addWidget(self.label_6, 2, 2, 1, 1)
        self.spinBoxDark = QtWidgets.QDoubleSpinBox(Dialog)
        self.spinBoxDark.setMaximum(100000.0)
        self.spinBoxDark.setProperty("value", 1600.0)
        self.spinBoxDark.setObjectName("spinBoxDark")
        self.gridLayoutNoise.addWidget(self.spinBoxDark, 3, 2, 1, 1)
        self.gridLayout.addLayout(self.gridLayoutNoise, 4, 0, 1, 2)
        self.frame = QtWidgets.QFrame(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 310))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelOutput = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelOutput.setFont(font)
        self.labelOutput.setObjectName("labelOutput")
        self.verticalLayout.addWidget(self.labelOutput)
        self.labelOutputSpace = QtWidgets.QLabel(self.frame)
        self.labelOutputSpace.setObjectName("labelOutputSpace")
        self.verticalLayout.addWidget(self.labelOutputSpace)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.spinBoxOutputRows = QtWidgets.QSpinBox(self.frame)
        self.spinBoxOutputRows.setReadOnly(True)
        self.spinBoxOutputRows.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxOutputRows.setMinimum(1)
        self.spinBoxOutputRows.setMaximum(100000)
        self.spinBoxOutputRows.setObjectName("spinBoxOutputRows")
        self.horizontalLayout.addWidget(self.spinBoxOutputRows)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.spinBoxOutputCols = QtWidgets.QSpinBox(self.frame)
        self.spinBoxOutputCols.setReadOnly(True)
        self.spinBoxOutputCols.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxOutputCols.setMinimum(1)
        self.spinBoxOutputCols.setMaximum(100000)
        self.spinBoxOutputCols.setObjectName("spinBoxOutputCols")
        self.horizontalLayout.addWidget(self.spinBoxOutputCols)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.labelOutputColors = QtWidgets.QLabel(self.frame)
        self.labelOutputColors.setObjectName("labelOutputColors")
        self.verticalLayout.addWidget(self.labelOutputColors)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.spinBoxOutputColors = QtWidgets.QSpinBox(self.frame)
        self.spinBoxOutputColors.setReadOnly(True)
        self.spinBoxOutputColors.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxOutputColors.setMinimum(1)
        self.spinBoxOutputColors.setMaximum(100000)
        self.spinBoxOutputColors.setObjectName("spinBoxOutputColors")
        self.horizontalLayout_2.addWidget(self.spinBoxOutputColors)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.spinBoxMemory = QtWidgets.QDoubleSpinBox(self.frame)
        self.spinBoxMemory.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxMemory.setDecimals(3)
        self.spinBoxMemory.setMaximum(100.0)
        self.spinBoxMemory.setObjectName("spinBoxMemory")
        self.verticalLayout.addWidget(self.spinBoxMemory)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.gridLayout.addWidget(self.frame, 3, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 310))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.labelInput = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelInput.setFont(font)
        self.labelInput.setObjectName("labelInput")
        self.verticalLayout_4.addWidget(self.labelInput)
        self.labelSubsample = QtWidgets.QLabel(self.frame_2)
        self.labelSubsample.setObjectName("labelSubsample")
        self.verticalLayout_4.addWidget(self.labelSubsample)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.spinBoxSubsample = QtWidgets.QSpinBox(self.frame_2)
        self.spinBoxSubsample.setMinimum(1)
        self.spinBoxSubsample.setMaximum(4)
        self.spinBoxSubsample.setProperty("value", 1)
        self.spinBoxSubsample.setObjectName("spinBoxSubsample")
        self.horizontalLayout_4.addWidget(self.spinBoxSubsample)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem6)
        self.labelWNRange = QtWidgets.QLabel(self.frame_2)
        self.labelWNRange.setObjectName("labelWNRange")
        self.verticalLayout_4.addWidget(self.labelWNRange)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelStart = QtWidgets.QLabel(self.frame_2)
        self.labelStart.setObjectName("labelStart")
        self.verticalLayout_2.addWidget(self.labelStart)
        self.spinBoxStart = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.spinBoxStart.setDecimals(1)
        self.spinBoxStart.setMaximum(5000.0)
        self.spinBoxStart.setSingleStep(100.0)
        self.spinBoxStart.setProperty("value", 500.0)
        self.spinBoxStart.setObjectName("spinBoxStart")
        self.verticalLayout_2.addWidget(self.spinBoxStart)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.labelEnd = QtWidgets.QLabel(self.frame_2)
        self.labelEnd.setObjectName("labelEnd")
        self.verticalLayout_3.addWidget(self.labelEnd)
        self.spinBoxEnd = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.spinBoxEnd.setDecimals(1)
        self.spinBoxEnd.setMaximum(5000.0)
        self.spinBoxEnd.setSingleStep(100.0)
        self.spinBoxEnd.setProperty("value", 4000.0)
        self.spinBoxEnd.setObjectName("spinBoxEnd")
        self.verticalLayout_3.addWidget(self.spinBoxEnd)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem8)
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.spinBoxSpectrographStep = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.spinBoxSpectrographStep.setDecimals(6)
        self.spinBoxSpectrographStep.setMinimum(-10.0)
        self.spinBoxSpectrographStep.setMaximum(10.0)
        self.spinBoxSpectrographStep.setSingleStep(0.1)
        self.spinBoxSpectrographStep.setProperty("value", -0.167741)
        self.spinBoxSpectrographStep.setObjectName("spinBoxSpectrographStep")
        self.horizontalLayout_5.addWidget(self.spinBoxSpectrographStep)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem9)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_4.addWidget(self.label_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.spinBoxProbe = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.spinBoxProbe.setDecimals(3)
        self.spinBoxProbe.setMinimum(200.0)
        self.spinBoxProbe.setMaximum(2000.0)
        self.spinBoxProbe.setProperty("value", 771.461)
        self.spinBoxProbe.setObjectName("spinBoxProbe")
        self.horizontalLayout_6.addWidget(self.spinBoxProbe)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem10)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem11)
        self.gridLayout.addWidget(self.frame_2, 3, 0, 1, 1)
        self.labelInfo = QtWidgets.QLabel(Dialog)
        self.labelInfo.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelInfo.setWordWrap(True)
        self.labelInfo.setObjectName("labelInfo")
        self.gridLayout.addWidget(self.labelInfo, 0, 0, 1, 2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButtonCancel = QtWidgets.QPushButton(Dialog)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayout_7.addWidget(self.pushButtonCancel)
        self.pushButtonOk = QtWidgets.QPushButton(Dialog)
        self.pushButtonOk.setObjectName("pushButtonOk")
        self.horizontalLayout_7.addWidget(self.pushButtonOk)
        self.gridLayout.addLayout(self.horizontalLayout_7, 5, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Generate Phantom"))
        self.label_4.setText(_translate("Dialog", "Std Dev"))
        self.label_5.setText(_translate("Dialog", "Multiplier (alpha)"))
        self.checkBoxPNoise.setText(_translate("Dialog", "Poisson"))
        self.checkBoxGNoise.setText(_translate("Dialog", "Gaussian (AWGN)"))
        self.label_2.setText(_translate("Dialog", "Add Noise / Dark"))
        self.checkBoxDark.setText(_translate("Dialog", "Dark Constant"))
        self.label_6.setText(_translate("Dialog", "Level"))
        self.labelOutput.setText(_translate("Dialog", "Output"))
        self.labelOutputSpace.setText(_translate("Dialog", "Spatial Pixels (M x N)"))
        self.label_3.setText(_translate("Dialog", "x"))
        self.labelOutputColors.setText(_translate("Dialog", "Frequencies/Colors"))
        self.label_8.setText(_translate("Dialog", "Dataset Size (Gb, Approx)"))
        self.labelInput.setText(_translate("Dialog", "Input"))
        self.labelSubsample.setText(_translate("Dialog", "Subsample (1x = Full Size)"))
        self.labelWNRange.setText(_translate("Dialog", "Wavenumber Range (cm-1)"))
        self.labelStart.setText(_translate("Dialog", "Start (Approx)"))
        self.labelEnd.setText(_translate("Dialog", "End (Approx)"))
        self.label.setText(_translate("Dialog", "Spectrograph Pixel Spacing (nm/pix)"))
        self.label_7.setText(_translate("Dialog", "Probe wavelength (nm)"))
        self.labelInfo.setText(_translate("Dialog", "This tool will generate a numerical \"phantom\". The default size is 300 x 300 pixels with 914 frequencies (\"colors\"). To work with a smaller model, you may choose fewer frequencies, a smaller spectral window, or subsample the spatial components."))
        self.pushButtonCancel.setText(_translate("Dialog", "Cancel"))
        self.pushButtonOk.setText(_translate("Dialog", "Ok"))

