# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_PlotEffect_KK.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(752, 215)
        Form.setStyleSheet("font: 10pt \"Arial\";")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setContentsMargins(-1, -1, 20, -1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_8.addWidget(self.label_6, 0, QtCore.Qt.AlignVCenter)
        self.spinBoxCARSBias = QtWidgets.QDoubleSpinBox(Form)
        self.spinBoxCARSBias.setMinimum(-100000.0)
        self.spinBoxCARSBias.setMaximum(100000.0)
        self.spinBoxCARSBias.setProperty("value", 0.0)
        self.spinBoxCARSBias.setObjectName("spinBoxCARSBias")
        self.verticalLayout_8.addWidget(self.spinBoxCARSBias, 0, QtCore.Qt.AlignVCenter)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_8)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.spinBoxNRBBias = QtWidgets.QDoubleSpinBox(Form)
        self.spinBoxNRBBias.setMinimum(-100000.0)
        self.spinBoxNRBBias.setMaximum(100000.0)
        self.spinBoxNRBBias.setObjectName("spinBoxNRBBias")
        self.verticalLayout.addWidget(self.spinBoxNRBBias)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.spinBoxPhaseLin = QtWidgets.QDoubleSpinBox(Form)
        self.spinBoxPhaseLin.setObjectName("spinBoxPhaseLin")
        self.verticalLayout_4.addWidget(self.spinBoxPhaseLin)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.checkBoxConjugate = QtWidgets.QCheckBox(self.frame)
        self.checkBoxConjugate.setObjectName("checkBoxConjugate")
        self.verticalLayout_5.addWidget(self.checkBoxConjugate)
        self.checkBoxNRBNorm = QtWidgets.QCheckBox(self.frame)
        self.checkBoxNRBNorm.setChecked(True)
        self.checkBoxNRBNorm.setObjectName("checkBoxNRBNorm")
        self.verticalLayout_5.addWidget(self.checkBoxNRBNorm)
        self.checkBoxLockBias = QtWidgets.QCheckBox(self.frame)
        self.checkBoxLockBias.setChecked(True)
        self.checkBoxLockBias.setObjectName("checkBoxLockBias")
        self.verticalLayout_5.addWidget(self.checkBoxLockBias)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.spinBoxPadFactor = QtWidgets.QSpinBox(self.frame)
        self.spinBoxPadFactor.setEnabled(True)
        self.spinBoxPadFactor.setKeyboardTracking(False)
        self.spinBoxPadFactor.setMaximum(30)
        self.spinBoxPadFactor.setProperty("value", 1)
        self.spinBoxPadFactor.setObjectName("spinBoxPadFactor")
        self.horizontalLayout_2.addWidget(self.spinBoxPadFactor)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.spinBoxEdge = QtWidgets.QSpinBox(self.frame)
        self.spinBoxEdge.setMinimum(1)
        self.spinBoxEdge.setMaximum(800)
        self.spinBoxEdge.setObjectName("spinBoxEdge")
        self.horizontalLayout_3.addWidget(self.spinBoxEdge)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.checkBoxShowReal = QtWidgets.QCheckBox(self.frame)
        self.checkBoxShowReal.setObjectName("checkBoxShowReal")
        self.verticalLayout_5.addWidget(self.checkBoxShowReal)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_6.setText(_translate("Form", "CARS Bias"))
        self.label_9.setText(_translate("Form", "NRB Bias"))
        self.label.setText(_translate("Form", "Phase Bias"))
        self.label_4.setText(_translate("Form", "Options"))
        self.checkBoxConjugate.setText(_translate("Form", "Conjugate"))
        self.checkBoxNRBNorm.setText(_translate("Form", "Norm to NRB"))
        self.checkBoxLockBias.setText(_translate("Form", "Lock NRB-to-CARS Bias"))
        self.label_5.setText(_translate("Form", "Pad Factor"))
        self.label_2.setText(_translate("Form", "N Edge Pix (Avg)"))
        self.checkBoxShowReal.setText(_translate("Form", "Show Real Part"))
