# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_PlotEffect_MergeNRBs.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(752, 260)
        Form.setStyleSheet("font: 10pt \"Arial\";")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.comboBoxScaleBlueRed = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBoxScaleBlueRed.setObjectName("comboBoxScaleBlueRed")
        self.comboBoxScaleBlueRed.addItem("")
        self.comboBoxScaleBlueRed.addItem("")
        self.verticalLayout_4.addWidget(self.comboBoxScaleBlueRed)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.doubleSpinBoxWN = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBoxWN.setMinimum(-10000.0)
        self.doubleSpinBoxWN.setMaximum(10000.0)
        self.doubleSpinBoxWN.setProperty("value", 3000.0)
        self.doubleSpinBoxWN.setObjectName("doubleSpinBoxWN")
        self.verticalLayout_4.addWidget(self.doubleSpinBoxWN)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_4.addWidget(self.label_7)
        self.doubleSpinBoxPixel = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBoxPixel.setMaximum(10000.0)
        self.doubleSpinBoxPixel.setProperty("value", 1427.0)
        self.doubleSpinBoxPixel.setObjectName("doubleSpinBoxPixel")
        self.verticalLayout_4.addWidget(self.doubleSpinBoxPixel)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setMaximumSize(QtCore.QSize(16777215, 12))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.spinBoxCARSBias = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.spinBoxCARSBias.setMaximumSize(QtCore.QSize(16777215, 20))
        self.spinBoxCARSBias.setKeyboardTracking(False)
        self.spinBoxCARSBias.setMinimum(-10000.0)
        self.spinBoxCARSBias.setMaximum(10000.0)
        self.spinBoxCARSBias.setObjectName("spinBoxCARSBias")
        self.verticalLayout.addWidget(self.spinBoxCARSBias, 0, QtCore.Qt.AlignHCenter)
        self.sliderCARSBias = QtWidgets.QSlider(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliderCARSBias.sizePolicy().hasHeightForWidth())
        self.sliderCARSBias.setSizePolicy(sizePolicy)
        self.sliderCARSBias.setMinimumSize(QtCore.QSize(0, 0))
        self.sliderCARSBias.setMinimum(-10000)
        self.sliderCARSBias.setMaximum(10000)
        self.sliderCARSBias.setOrientation(QtCore.Qt.Vertical)
        self.sliderCARSBias.setObjectName("sliderCARSBias")
        self.verticalLayout.addWidget(self.sliderCARSBias, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 12))
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.spinBoxNRBBias = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.spinBoxNRBBias.setMaximumSize(QtCore.QSize(16777215, 20))
        self.spinBoxNRBBias.setKeyboardTracking(False)
        self.spinBoxNRBBias.setMinimum(-10000.0)
        self.spinBoxNRBBias.setMaximum(10000.0)
        self.spinBoxNRBBias.setObjectName("spinBoxNRBBias")
        self.verticalLayout_2.addWidget(self.spinBoxNRBBias, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.sliderNRBBias = QtWidgets.QSlider(self.groupBox)
        self.sliderNRBBias.setMinimumSize(QtCore.QSize(0, 100))
        self.sliderNRBBias.setMinimum(-10000)
        self.sliderNRBBias.setMaximum(10000)
        self.sliderNRBBias.setOrientation(QtCore.Qt.Vertical)
        self.sliderNRBBias.setObjectName("sliderNRBBias")
        self.verticalLayout_2.addWidget(self.sliderNRBBias, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter)
        self.spinBoxPhaseLin = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.spinBoxPhaseLin.setMaximumSize(QtCore.QSize(16777215, 20))
        self.spinBoxPhaseLin.setKeyboardTracking(False)
        self.spinBoxPhaseLin.setMinimum(-720.0)
        self.spinBoxPhaseLin.setMaximum(720.0)
        self.spinBoxPhaseLin.setObjectName("spinBoxPhaseLin")
        self.verticalLayout_3.addWidget(self.spinBoxPhaseLin)
        self.sliderPhaseLin = QtWidgets.QSlider(self.groupBox)
        self.sliderPhaseLin.setMinimum(-720)
        self.sliderPhaseLin.setMaximum(720)
        self.sliderPhaseLin.setOrientation(QtCore.Qt.Vertical)
        self.sliderPhaseLin.setObjectName("sliderPhaseLin")
        self.verticalLayout_3.addWidget(self.sliderPhaseLin, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.frame = QtWidgets.QFrame(self.groupBox)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.checkBoxNRBNorm = QtWidgets.QCheckBox(self.frame)
        self.checkBoxNRBNorm.setChecked(True)
        self.checkBoxNRBNorm.setObjectName("checkBoxNRBNorm")
        self.verticalLayout_5.addWidget(self.checkBoxNRBNorm)
        self.checkBoxLockBias = QtWidgets.QCheckBox(self.frame)
        self.checkBoxLockBias.setChecked(True)
        self.checkBoxLockBias.setObjectName("checkBoxLockBias")
        self.verticalLayout_5.addWidget(self.checkBoxLockBias)
        self.radioButtonPhaseLin = QtWidgets.QRadioButton(self.frame)
        self.radioButtonPhaseLin.setChecked(True)
        self.radioButtonPhaseLin.setObjectName("radioButtonPhaseLin")
        self.verticalLayout_5.addWidget(self.radioButtonPhaseLin)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.spinBoxPadFactor = QtWidgets.QSpinBox(self.frame)
        self.spinBoxPadFactor.setEnabled(True)
        self.spinBoxPadFactor.setKeyboardTracking(False)
        self.spinBoxPadFactor.setMaximum(30)
        self.spinBoxPadFactor.setProperty("value", 1)
        self.spinBoxPadFactor.setObjectName("spinBoxPadFactor")
        self.horizontalLayout_2.addWidget(self.spinBoxPadFactor)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addWidget(self.frame)
        self.horizontalLayout.addWidget(self.groupBox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_2.setTitle(_translate("Form", "Merge Parameters"))
        self.comboBoxScaleBlueRed.setItemText(0, _translate("Form", "Scale Blue NRB"))
        self.comboBoxScaleBlueRed.setItemText(1, _translate("Form", "Scale Red NRB"))
        self.label_6.setText(_translate("Form", "Wavenumber"))
        self.label_7.setText(_translate("Form", "Pixel Number"))
        self.groupBox.setTitle(_translate("Form", "Kramers-Kronig Parameters"))
        self.label.setText(_translate("Form", "CARS Bias"))
        self.label_2.setText(_translate("Form", "NRB Bias"))
        self.label_3.setText(_translate("Form", "Phase Bias"))
        self.label_4.setText(_translate("Form", "Options"))
        self.checkBoxNRBNorm.setText(_translate("Form", "Norm to NRB"))
        self.checkBoxLockBias.setText(_translate("Form", "Lock NRB-to-CARS Bias"))
        self.radioButtonPhaseLin.setText(_translate("Form", "Linear Phase"))
        self.label_5.setText(_translate("Form", "Pad Factor"))

