# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_PlotEffect_KK.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(752, 260)
        Form.setStyleSheet("font: 10pt \"Arial\";")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setMaximumSize(QtCore.QSize(16777215, 12))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.spinBoxCARSBias = QtWidgets.QDoubleSpinBox(Form)
        self.spinBoxCARSBias.setMaximumSize(QtCore.QSize(16777215, 20))
        self.spinBoxCARSBias.setKeyboardTracking(False)
        self.spinBoxCARSBias.setMinimum(-10000.0)
        self.spinBoxCARSBias.setMaximum(10000.0)
        self.spinBoxCARSBias.setObjectName("spinBoxCARSBias")
        self.verticalLayout.addWidget(self.spinBoxCARSBias, 0, QtCore.Qt.AlignHCenter)
        self.sliderCARSBias = QtWidgets.QSlider(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliderCARSBias.sizePolicy().hasHeightForWidth())
        self.sliderCARSBias.setSizePolicy(sizePolicy)
        self.sliderCARSBias.setMinimumSize(QtCore.QSize(0, 0))
        self.sliderCARSBias.setMinimum(-10000)
        self.sliderCARSBias.setMaximum(10000)
        self.sliderCARSBias.setOrientation(QtCore.Qt.Vertical)
        self.sliderCARSBias.setObjectName("sliderCARSBias")
        self.verticalLayout.addWidget(self.sliderCARSBias, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 12))
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.spinBoxNRBBias = QtWidgets.QDoubleSpinBox(Form)
        self.spinBoxNRBBias.setMaximumSize(QtCore.QSize(16777215, 20))
        self.spinBoxNRBBias.setKeyboardTracking(False)
        self.spinBoxNRBBias.setMinimum(-10000.0)
        self.spinBoxNRBBias.setMaximum(10000.0)
        self.spinBoxNRBBias.setObjectName("spinBoxNRBBias")
        self.verticalLayout_2.addWidget(self.spinBoxNRBBias, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.sliderNRBBias = QtWidgets.QSlider(Form)
        self.sliderNRBBias.setMinimumSize(QtCore.QSize(0, 100))
        self.sliderNRBBias.setMinimum(-10000)
        self.sliderNRBBias.setMaximum(10000)
        self.sliderNRBBias.setOrientation(QtCore.Qt.Vertical)
        self.sliderNRBBias.setObjectName("sliderNRBBias")
        self.verticalLayout_2.addWidget(self.sliderNRBBias, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tabLin = QtWidgets.QWidget()
        self.tabLin.setObjectName("tabLin")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tabLin)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.spinBoxPhaseLin = QtWidgets.QDoubleSpinBox(self.tabLin)
        self.spinBoxPhaseLin.setMaximumSize(QtCore.QSize(16777215, 20))
        self.spinBoxPhaseLin.setKeyboardTracking(False)
        self.spinBoxPhaseLin.setMinimum(-720.0)
        self.spinBoxPhaseLin.setMaximum(720.0)
        self.spinBoxPhaseLin.setObjectName("spinBoxPhaseLin")
        self.verticalLayout_4.addWidget(self.spinBoxPhaseLin, 0, QtCore.Qt.AlignHCenter)
        self.sliderPhaseLin = QtWidgets.QSlider(self.tabLin)
        self.sliderPhaseLin.setMinimum(-720)
        self.sliderPhaseLin.setMaximum(720)
        self.sliderPhaseLin.setOrientation(QtCore.Qt.Vertical)
        self.sliderPhaseLin.setObjectName("sliderPhaseLin")
        self.verticalLayout_4.addWidget(self.sliderPhaseLin, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.tabWidget.addTab(self.tabLin, "")
        self.tabSigmoidal = QtWidgets.QWidget()
        self.tabSigmoidal.setObjectName("tabSigmoidal")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tabSigmoidal)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.tabSigmoidal)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 12))
        self.label_7.setObjectName("label_7")
        self.verticalLayout_6.addWidget(self.label_7, 0, QtCore.Qt.AlignHCenter)
        self.spinBoxSigPhase1 = QtWidgets.QDoubleSpinBox(self.tabSigmoidal)
        self.spinBoxSigPhase1.setMaximumSize(QtCore.QSize(16777215, 20))
        self.spinBoxSigPhase1.setKeyboardTracking(False)
        self.spinBoxSigPhase1.setMinimum(-720.0)
        self.spinBoxSigPhase1.setMaximum(720.0)
        self.spinBoxSigPhase1.setObjectName("spinBoxSigPhase1")
        self.verticalLayout_6.addWidget(self.spinBoxSigPhase1, 0, QtCore.Qt.AlignHCenter)
        self.sliderSigPhase1 = QtWidgets.QSlider(self.tabSigmoidal)
        self.sliderSigPhase1.setEnabled(True)
        self.sliderSigPhase1.setMinimum(-720)
        self.sliderSigPhase1.setMaximum(720)
        self.sliderSigPhase1.setOrientation(QtCore.Qt.Vertical)
        self.sliderSigPhase1.setObjectName("sliderSigPhase1")
        self.verticalLayout_6.addWidget(self.sliderSigPhase1, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_5.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.tabSigmoidal)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 12))
        self.label_8.setObjectName("label_8")
        self.verticalLayout_7.addWidget(self.label_8, 0, QtCore.Qt.AlignHCenter)
        self.spinBoxSigPhase2 = QtWidgets.QDoubleSpinBox(self.tabSigmoidal)
        self.spinBoxSigPhase2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.spinBoxSigPhase2.setKeyboardTracking(False)
        self.spinBoxSigPhase2.setMinimum(-720.0)
        self.spinBoxSigPhase2.setMaximum(720.0)
        self.spinBoxSigPhase2.setObjectName("spinBoxSigPhase2")
        self.verticalLayout_7.addWidget(self.spinBoxSigPhase2, 0, QtCore.Qt.AlignHCenter)
        self.sliderSigPhase2 = QtWidgets.QSlider(self.tabSigmoidal)
        self.sliderSigPhase2.setMinimum(-720)
        self.sliderSigPhase2.setMaximum(720)
        self.sliderSigPhase2.setOrientation(QtCore.Qt.Vertical)
        self.sliderSigPhase2.setObjectName("sliderSigPhase2")
        self.verticalLayout_7.addWidget(self.sliderSigPhase2, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_5.addLayout(self.verticalLayout_7)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.tabSigmoidal)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 12))
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter)
        self.spinBoxSigRate = QtWidgets.QDoubleSpinBox(self.tabSigmoidal)
        self.spinBoxSigRate.setMaximumSize(QtCore.QSize(16777215, 20))
        self.spinBoxSigRate.setKeyboardTracking(False)
        self.spinBoxSigRate.setMaximum(10.0)
        self.spinBoxSigRate.setSingleStep(0.001)
        self.spinBoxSigRate.setProperty("value", 0.1)
        self.spinBoxSigRate.setObjectName("spinBoxSigRate")
        self.verticalLayout_3.addWidget(self.spinBoxSigRate, 0, QtCore.Qt.AlignHCenter)
        self.sliderSigRate = QtWidgets.QSlider(self.tabSigmoidal)
        self.sliderSigRate.setMaximum(10000)
        self.sliderSigRate.setProperty("value", 1)
        self.sliderSigRate.setOrientation(QtCore.Qt.Vertical)
        self.sliderSigRate.setObjectName("sliderSigRate")
        self.verticalLayout_3.addWidget(self.sliderSigRate, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.tabWidget.addTab(self.tabSigmoidal, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.checkBoxNRBNorm = QtWidgets.QCheckBox(self.frame)
        self.checkBoxNRBNorm.setChecked(True)
        self.checkBoxNRBNorm.setObjectName("checkBoxNRBNorm")
        self.verticalLayout_5.addWidget(self.checkBoxNRBNorm)
        self.checkBoxLockBias = QtWidgets.QCheckBox(self.frame)
        self.checkBoxLockBias.setChecked(True)
        self.checkBoxLockBias.setObjectName("checkBoxLockBias")
        self.verticalLayout_5.addWidget(self.checkBoxLockBias)
        self.radioButtonPhaseLin = QtWidgets.QRadioButton(self.frame)
        self.radioButtonPhaseLin.setChecked(True)
        self.radioButtonPhaseLin.setObjectName("radioButtonPhaseLin")
        self.verticalLayout_5.addWidget(self.radioButtonPhaseLin)
        self.radioButtonPhaseSig = QtWidgets.QRadioButton(self.frame)
        self.radioButtonPhaseSig.setObjectName("radioButtonPhaseSig")
        self.verticalLayout_5.addWidget(self.radioButtonPhaseSig)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.spinBoxPadFactor = QtWidgets.QSpinBox(self.frame)
        self.spinBoxPadFactor.setEnabled(True)
        self.spinBoxPadFactor.setKeyboardTracking(False)
        self.spinBoxPadFactor.setMaximum(30)
        self.spinBoxPadFactor.setProperty("value", 1)
        self.spinBoxPadFactor.setObjectName("spinBoxPadFactor")
        self.horizontalLayout_2.addWidget(self.spinBoxPadFactor)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "CARS Bias"))
        self.label_2.setText(_translate("Form", "NRB Bias"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabLin), _translate("Form", "Phase (Linear)"))
        self.label_7.setText(_translate("Form", "Phase 1"))
        self.label_8.setText(_translate("Form", "Phase 2"))
        self.label_3.setText(_translate("Form", "Rate"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSigmoidal), _translate("Form", "Phase (Sigmoidal)"))
        self.label_4.setText(_translate("Form", "Options"))
        self.checkBoxNRBNorm.setText(_translate("Form", "Norm to NRB"))
        self.checkBoxLockBias.setText(_translate("Form", "Lock NRB-to-CARS Bias"))
        self.radioButtonPhaseLin.setText(_translate("Form", "Linear Phase"))
        self.radioButtonPhaseSig.setText(_translate("Form", "Sigmoidal Phase"))
        self.label_5.setText(_translate("Form", "Pad Factor"))

