# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_PlotEffect_Calibrate.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 300)
        Form.setStyleSheet("font: 10pt \"Arial\";")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(2)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 2, 0, 1, 1)
        self.spinBoxNPix = QtWidgets.QSpinBox(self.frame)
        self.spinBoxNPix.setReadOnly(True)
        self.spinBoxNPix.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxNPix.setKeyboardTracking(False)
        self.spinBoxNPix.setMinimum(1)
        self.spinBoxNPix.setMaximum(100000)
        self.spinBoxNPix.setProperty("value", 1600)
        self.spinBoxNPix.setObjectName("spinBoxNPix")
        self.gridLayout_2.addWidget(self.spinBoxNPix, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 2, 1, 1)
        self.spinBoxCenterWL = QtWidgets.QDoubleSpinBox(self.frame)
        self.spinBoxCenterWL.setReadOnly(True)
        self.spinBoxCenterWL.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxCenterWL.setKeyboardTracking(False)
        self.spinBoxCenterWL.setDecimals(3)
        self.spinBoxCenterWL.setMaximum(1000000.0)
        self.spinBoxCenterWL.setSingleStep(100.0)
        self.spinBoxCenterWL.setProperty("value", 730.0)
        self.spinBoxCenterWL.setObjectName("spinBoxCenterWL")
        self.gridLayout_2.addWidget(self.spinBoxCenterWL, 1, 1, 1, 1)
        self.spinBoxCalibWL = QtWidgets.QDoubleSpinBox(self.frame)
        self.spinBoxCalibWL.setReadOnly(True)
        self.spinBoxCalibWL.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxCalibWL.setKeyboardTracking(False)
        self.spinBoxCalibWL.setDecimals(3)
        self.spinBoxCalibWL.setMaximum(10000.0)
        self.spinBoxCalibWL.setProperty("value", 730.0)
        self.spinBoxCalibWL.setObjectName("spinBoxCalibWL")
        self.gridLayout_2.addWidget(self.spinBoxCalibWL, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.spinBoxSlope = QtWidgets.QDoubleSpinBox(self.frame)
        self.spinBoxSlope.setReadOnly(True)
        self.spinBoxSlope.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxSlope.setDecimals(3)
        self.spinBoxSlope.setMinimum(-100000.0)
        self.spinBoxSlope.setMaximum(100000.0)
        self.spinBoxSlope.setProperty("value", -0.168)
        self.spinBoxSlope.setObjectName("spinBoxSlope")
        self.gridLayout_2.addWidget(self.spinBoxSlope, 4, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 3, 1, 1, 1)
        self.spinBoxIntercept = QtWidgets.QDoubleSpinBox(self.frame)
        self.spinBoxIntercept.setReadOnly(True)
        self.spinBoxIntercept.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxIntercept.setDecimals(3)
        self.spinBoxIntercept.setMinimum(-1000000.0)
        self.spinBoxIntercept.setMaximum(1000000.0)
        self.spinBoxIntercept.setProperty("value", 863.874)
        self.spinBoxIntercept.setObjectName("spinBoxIntercept")
        self.gridLayout_2.addWidget(self.spinBoxIntercept, 4, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 3, 2, 1, 1)
        self.spinBoxProbeWL = QtWidgets.QDoubleSpinBox(self.frame)
        self.spinBoxProbeWL.setReadOnly(True)
        self.spinBoxProbeWL.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxProbeWL.setDecimals(3)
        self.spinBoxProbeWL.setMaximum(10000.0)
        self.spinBoxProbeWL.setProperty("value", 771.461)
        self.spinBoxProbeWL.setObjectName("spinBoxProbeWL")
        self.gridLayout_2.addWidget(self.spinBoxProbeWL, 4, 2, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setObjectName("label_14")
        self.verticalLayout.addWidget(self.label_14)
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setLineWidth(2)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 2, 0, 1, 1)
        self.spinBoxNPix_2 = QtWidgets.QSpinBox(self.frame_2)
        self.spinBoxNPix_2.setFrame(True)
        self.spinBoxNPix_2.setReadOnly(False)
        self.spinBoxNPix_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinBoxNPix_2.setKeyboardTracking(False)
        self.spinBoxNPix_2.setMinimum(1)
        self.spinBoxNPix_2.setMaximum(100000)
        self.spinBoxNPix_2.setProperty("value", 1600)
        self.spinBoxNPix_2.setObjectName("spinBoxNPix_2")
        self.gridLayout_3.addWidget(self.spinBoxNPix_2, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 2, 1, 1)
        self.spinBoxCenterWL_2 = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.spinBoxCenterWL_2.setFrame(True)
        self.spinBoxCenterWL_2.setReadOnly(False)
        self.spinBoxCenterWL_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinBoxCenterWL_2.setKeyboardTracking(False)
        self.spinBoxCenterWL_2.setDecimals(3)
        self.spinBoxCenterWL_2.setMaximum(1000000.0)
        self.spinBoxCenterWL_2.setSingleStep(100.0)
        self.spinBoxCenterWL_2.setProperty("value", 730.0)
        self.spinBoxCenterWL_2.setObjectName("spinBoxCenterWL_2")
        self.gridLayout_3.addWidget(self.spinBoxCenterWL_2, 1, 1, 1, 1)
        self.spinBoxCalibWL_2 = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.spinBoxCalibWL_2.setFrame(True)
        self.spinBoxCalibWL_2.setReadOnly(False)
        self.spinBoxCalibWL_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinBoxCalibWL_2.setKeyboardTracking(False)
        self.spinBoxCalibWL_2.setDecimals(3)
        self.spinBoxCalibWL_2.setMaximum(10000.0)
        self.spinBoxCalibWL_2.setProperty("value", 730.0)
        self.spinBoxCalibWL_2.setObjectName("spinBoxCalibWL_2")
        self.gridLayout_3.addWidget(self.spinBoxCalibWL_2, 1, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 3, 0, 1, 1)
        self.spinBoxSlope_2 = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.spinBoxSlope_2.setFrame(True)
        self.spinBoxSlope_2.setReadOnly(False)
        self.spinBoxSlope_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinBoxSlope_2.setDecimals(3)
        self.spinBoxSlope_2.setMinimum(-100000.0)
        self.spinBoxSlope_2.setMaximum(100000.0)
        self.spinBoxSlope_2.setProperty("value", -0.168)
        self.spinBoxSlope_2.setObjectName("spinBoxSlope_2")
        self.gridLayout_3.addWidget(self.spinBoxSlope_2, 4, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 3, 1, 1, 1)
        self.spinBoxIntercept_2 = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.spinBoxIntercept_2.setFrame(True)
        self.spinBoxIntercept_2.setReadOnly(False)
        self.spinBoxIntercept_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinBoxIntercept_2.setDecimals(3)
        self.spinBoxIntercept_2.setMinimum(-1000000.0)
        self.spinBoxIntercept_2.setMaximum(1000000.0)
        self.spinBoxIntercept_2.setProperty("value", 863.874)
        self.spinBoxIntercept_2.setObjectName("spinBoxIntercept_2")
        self.gridLayout_3.addWidget(self.spinBoxIntercept_2, 4, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.frame_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 3, 2, 1, 1)
        self.spinBoxProbeWL_2 = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.spinBoxProbeWL_2.setFrame(True)
        self.spinBoxProbeWL_2.setReadOnly(False)
        self.spinBoxProbeWL_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinBoxProbeWL_2.setDecimals(3)
        self.spinBoxProbeWL_2.setMaximum(10000.0)
        self.spinBoxProbeWL_2.setProperty("value", 771.461)
        self.spinBoxProbeWL_2.setObjectName("spinBoxProbeWL_2")
        self.gridLayout_3.addWidget(self.spinBoxProbeWL_2, 4, 2, 1, 1)
        self.verticalLayout.addWidget(self.frame_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setLineWidth(2)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_15 = QtWidgets.QLabel(self.frame_3)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_2.addWidget(self.label_15)
        self.spinBoxMeas = QtWidgets.QDoubleSpinBox(self.frame_3)
        self.spinBoxMeas.setDecimals(3)
        self.spinBoxMeas.setMaximum(10000000.0)
        self.spinBoxMeas.setProperty("value", 1004.0)
        self.spinBoxMeas.setObjectName("spinBoxMeas")
        self.verticalLayout_2.addWidget(self.spinBoxMeas)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.label_16 = QtWidgets.QLabel(self.frame_3)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_2.addWidget(self.label_16)
        self.spinBoxCorrect = QtWidgets.QDoubleSpinBox(self.frame_3)
        self.spinBoxCorrect.setMaximum(10000000.0)
        self.spinBoxCorrect.setProperty("value", 1004.0)
        self.spinBoxCorrect.setObjectName("spinBoxCorrect")
        self.verticalLayout_2.addWidget(self.spinBoxCorrect)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.horizontalLayout.addWidget(self.frame_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_13.setText(_translate("Form", "Current"))
        self.label.setText(_translate("Form", "Number Pixels"))
        self.label_2.setText(_translate("Form", "Center Wavelength (nm)"))
        self.label_3.setText(_translate("Form", "Calibration Wavelength (nm)"))
        self.label_4.setText(_translate("Form", "Slope (nm/pixel)"))
        self.label_5.setText(_translate("Form", "Intercept (nm)"))
        self.label_6.setText(_translate("Form", "Probe Wavelength (nm)"))
        self.label_14.setText(_translate("Form", "Altered"))
        self.label_7.setText(_translate("Form", "Number Pixels"))
        self.label_8.setText(_translate("Form", "Center Wavelength (nm)"))
        self.label_9.setText(_translate("Form", "Calibration Wavelength (nm)"))
        self.label_10.setText(_translate("Form", "Slope (nm/pixel)"))
        self.label_11.setText(_translate("Form", "Intercept (nm)"))
        self.label_12.setText(_translate("Form", "Probe Wavelength (nm)"))
        self.label_15.setText(_translate("Form", "Measured WN"))
        self.label_16.setText(_translate("Form", "Correct WN"))


