# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_Save.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(674, 410)
        Dialog.setStyleSheet("font: 10pt \"Arial\";")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonGetFilename = QtWidgets.QToolButton(Dialog)
        self.buttonGetFilename.setObjectName("buttonGetFilename")
        self.horizontalLayout.addWidget(self.buttonGetFilename)
        self.lineEditFilename = QtWidgets.QLineEdit(Dialog)
        self.lineEditFilename.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEditFilename.setObjectName("lineEditFilename")
        self.horizontalLayout.addWidget(self.lineEditFilename)
        self.buttonGenerateFilename = QtWidgets.QToolButton(Dialog)
        self.buttonGenerateFilename.setObjectName("buttonGenerateFilename")
        self.horizontalLayout.addWidget(self.buttonGenerateFilename)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, -1, 10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.buttonGetPath = QtWidgets.QToolButton(Dialog)
        self.buttonGetPath.setObjectName("buttonGetPath")
        self.horizontalLayout_2.addWidget(self.buttonGetPath)
        self.lineEditPath = QtWidgets.QLineEdit(Dialog)
        self.lineEditPath.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEditPath.setObjectName("lineEditPath")
        self.horizontalLayout_2.addWidget(self.lineEditPath)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEditDataset = QtWidgets.QLineEdit(Dialog)
        self.lineEditDataset.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEditDataset.setObjectName("lineEditDataset")
        self.horizontalLayout_4.addWidget(self.lineEditDataset)
        self.buttonGenerateDatasetname = QtWidgets.QToolButton(Dialog)
        self.buttonGenerateDatasetname.setObjectName("buttonGenerateDatasetname")
        self.horizontalLayout_4.addWidget(self.buttonGenerateDatasetname)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.lineReadFileNamePath = QtWidgets.QLineEdit(self.frame)
        self.lineReadFileNamePath.setEnabled(False)
        self.lineReadFileNamePath.setReadOnly(True)
        self.lineReadFileNamePath.setObjectName("lineReadFileNamePath")
        self.verticalLayout_3.addWidget(self.lineReadFileNamePath)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.lineReadDataset = QtWidgets.QLineEdit(self.frame)
        self.lineReadDataset.setEnabled(False)
        self.lineReadDataset.setReadOnly(True)
        self.lineReadDataset.setObjectName("lineReadDataset")
        self.verticalLayout_3.addWidget(self.lineReadDataset)
        self.verticalLayout.addWidget(self.frame)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, -1, -1, 10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.buttonOK = QtWidgets.QToolButton(Dialog)
        self.buttonOK.setMinimumSize(QtCore.QSize(100, 0))
        self.buttonOK.setMaximumSize(QtCore.QSize(100, 16777215))
        self.buttonOK.setBaseSize(QtCore.QSize(0, 0))
        self.buttonOK.setObjectName("buttonOK")
        self.horizontalLayout_3.addWidget(self.buttonOK)
        self.buttonCancel = QtWidgets.QToolButton(Dialog)
        self.buttonCancel.setMinimumSize(QtCore.QSize(100, 0))
        self.buttonCancel.setMaximumSize(QtCore.QSize(100, 16777215))
        self.buttonCancel.setObjectName("buttonCancel")
        self.horizontalLayout_3.addWidget(self.buttonCancel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.buttonGetFilename, self.buttonGenerateFilename)
        Dialog.setTabOrder(self.buttonGenerateFilename, self.buttonGetPath)
        Dialog.setTabOrder(self.buttonGetPath, self.lineReadFileNamePath)
        Dialog.setTabOrder(self.lineReadFileNamePath, self.lineReadDataset)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Save"))
        self.label.setText(_translate("Dialog", "Filename"))
        self.buttonGetFilename.setText(_translate("Dialog", "..."))
        self.buttonGenerateFilename.setText(_translate("Dialog", "Generate"))
        self.label_2.setText(_translate("Dialog", "Path"))
        self.buttonGetPath.setText(_translate("Dialog", "..."))
        self.label_3.setText(_translate("Dialog", "Dataset Full Path and Name"))
        self.buttonGenerateDatasetname.setText(_translate("Dialog", "Generate"))
        self.label_4.setText(_translate("Dialog", "HDF5 Full Path and Name"))
        self.label_5.setText(_translate("Dialog", "Dataset Full Path and Name"))
        self.buttonOK.setText(_translate("Dialog", "OK"))
        self.buttonCancel.setText(_translate("Dialog", "Cancel"))

