# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_SglColorImage.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(642, 579)
        Form.setMouseTracking(False)
        Form.setStyleSheet("font: 10pt \"Arial\";")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayoutMain = QtWidgets.QVBoxLayout()
        self.verticalLayoutMain.setObjectName("verticalLayoutMain")
        self.widgetImgOpt = QtWidgets.QWidget(Form)
        self.widgetImgOpt.setEnabled(True)
        self.widgetImgOpt.setObjectName("widgetImgOpt")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widgetImgOpt)
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButtonPop = QtWidgets.QPushButton(self.widgetImgOpt)
        self.pushButtonPop.setEnabled(True)
        self.pushButtonPop.setObjectName("pushButtonPop")
        self.horizontalLayout_3.addWidget(self.pushButtonPop)
        self.pushButtonSpectrum = QtWidgets.QPushButton(self.widgetImgOpt)
        self.pushButtonSpectrum.setEnabled(True)
        self.pushButtonSpectrum.setObjectName("pushButtonSpectrum")
        self.horizontalLayout_3.addWidget(self.pushButtonSpectrum)
        self.pushButtonGSPop = QtWidgets.QPushButton(self.widgetImgOpt)
        self.pushButtonGSPop.setEnabled(True)
        self.pushButtonGSPop.setObjectName("pushButtonGSPop")
        self.horizontalLayout_3.addWidget(self.pushButtonGSPop)
        self.comboBox = QtWidgets.QComboBox(self.widgetImgOpt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setMinimumSize(QtCore.QSize(140, 0))
        self.comboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox.setEditable(False)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_3.addWidget(self.comboBox, 0, QtCore.Qt.AlignHCenter)
        self.pushButtonSpectrum.raise_()
        self.pushButtonGSPop.raise_()
        self.comboBox.raise_()
        self.pushButtonPop.raise_()
        self.verticalLayoutMain.addWidget(self.widgetImgOpt)
        self.horizontalLayoutGainImg = QtWidgets.QHBoxLayout()
        self.horizontalLayoutGainImg.setContentsMargins(10, -1, -1, -1)
        self.horizontalLayoutGainImg.setObjectName("horizontalLayoutGainImg")
        self.groupBox = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(120, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(120, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayoutGain = QtWidgets.QVBoxLayout()
        self.verticalLayoutGain.setContentsMargins(-1, 6, -1, -1)
        self.verticalLayoutGain.setSpacing(6)
        self.verticalLayoutGain.setObjectName("verticalLayoutGain")
        self.gainSlider = QtWidgets.QSlider(self.groupBox)
        self.gainSlider.setMaximum(100)
        self.gainSlider.setProperty("value", 10)
        self.gainSlider.setSliderPosition(10)
        self.gainSlider.setOrientation(QtCore.Qt.Vertical)
        self.gainSlider.setInvertedAppearance(False)
        self.gainSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.gainSlider.setTickInterval(10)
        self.gainSlider.setObjectName("gainSlider")
        self.verticalLayoutGain.addWidget(self.gainSlider, 0, QtCore.Qt.AlignHCenter)
        self.lineEditGainSlider = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditGainSlider.sizePolicy().hasHeightForWidth())
        self.lineEditGainSlider.setSizePolicy(sizePolicy)
        self.lineEditGainSlider.setMaximumSize(QtCore.QSize(30, 16777215))
        self.lineEditGainSlider.setObjectName("lineEditGainSlider")
        self.verticalLayoutGain.addWidget(self.lineEditGainSlider, 0, QtCore.Qt.AlignHCenter)
        self.pushButtonGain1 = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonGain1.setObjectName("pushButtonGain1")
        self.verticalLayoutGain.addWidget(self.pushButtonGain1, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_2.addLayout(self.verticalLayoutGain, 0, 0, 1, 1)
        self.horizontalLayoutGainImg.addWidget(self.groupBox)
        self.verticalLayoutMain.addLayout(self.horizontalLayoutGainImg)
        self.gridLayout.addLayout(self.verticalLayoutMain, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButtonPop.setText(_translate("Form", "Pop"))
        self.pushButtonSpectrum.setText(_translate("Form", "Spectrum"))
        self.pushButtonGSPop.setText(_translate("Form", "Grayscale"))
        self.groupBox.setTitle(_translate("Form", "Gain"))
        self.lineEditGainSlider.setText(_translate("Form", "1.0"))
        self.pushButtonGain1.setText(_translate("Form", "1.0"))

